class AppStrings {
  static const Map<String, Map<String, String>> _values = {
    'en': {
      'nav_work': 'WORK',
      'nav_about': 'ABOUT',
      'nav_services': 'SERVICES',
      'nav_talk': 'LET\'S TALK',
      'hero_badge': 'AVAILABLE FOR NEW OPPORTUNITIES',
      'hero_title': 'Mohamed Taha',
      'hero_subtitle': 'Senior Software Architect',
      'hero_description': 'Crafting resilient, high-performance digital ecosystems with Flutter, Android Native, and cutting-edge AI integrations.',
      'hero_cta_primary': 'Explore Projects',
      'hero_cta_secondary': 'Get in Touch',
      'about_label': 'Philosophy',
      'about_title': 'Engineering for the\nFuture of Mobility and AI.',
      'about_p1': 'My work is defined by the intersection of rigorous engineering and intuitive design. With a focus on performance-critical applications, I build systems that are robust enough for production but fluid enough for a premium user experience.',
      'about_p2': 'From AstraPlay\'s hardware-accelerated playback to Hisn Al Muslim\'s native background synchronization, I push the boundaries of what is possible with cross-platform frameworks.',
      'skills_title': 'Core Stack',
      'skills_subtitle': 'The tools I use to build world-class products.',
      'projects_title': 'Selected Work',
      'contact_title': 'Let\'s Connect',
      'contact_subtitle': 'Interested in collaboration or have a technical question? Reach out through any of the platforms below.',
      'back_to_projects': 'Back to Projects',
      'project_resources': 'Resources & Links',
      'project_role': 'Role',
      'project_tech': 'Tech Stack',
      'project_live': 'Live',
      'project_role_lead': 'Lead Engineer',
      'project_status_prod': 'Production Ready',
      'footer_rights': 'Built with Flutter Web.',
      'skill_flutter': 'Flutter',
      'skill_kotlin': 'Kotlin',
      'skill_isar': 'Isar/SQLite',
      'skill_firebase': 'Firebase',
      'skill_ai': 'AI Integration',
      'skill_perf': 'Perf/Security',
      'contact_email_label': 'Email',
      'contact_linkedin_label': 'LinkedIn',
      'contact_github_label': 'GitHub',
      'connect_button': 'Connect',
    },
    'ar': {
      'nav_work': 'أعمالي',
      'nav_about': 'عني',
      'nav_services': 'خدماتي',
      'nav_talk': 'تواصل معي',
      'hero_badge': 'متاح للفرص الجديدة',
      'hero_title': 'محمد طه',
      'hero_subtitle': 'كبير مهندسي البرمجيات',
      'hero_description': 'بناء أنظمة رقمية مرنة وعالية الأداء باستخدام Flutter و Android Native وتكاملات الذكاء الاصطناعي المتطورة.',
      'hero_cta_primary': 'استكشف المشاريع',
      'hero_cta_secondary': 'اتصل بي',
      'about_label': 'فلسفتي الهندسية',
      'about_title': 'الهندسة من أجل\nمستقبل التنقل والذكاء الاصطناعي.',
      'about_p1': 'يتم تعريف عملي من خلال التقاء الهندسة الصارمة والتصميم البديهي. مع التركيز على التطبيقات ذات الأداء الحرج، أقوم ببناء أنظمة قوية بما يكفي للإنتاج ولكنها سلسة بما يكفي لتجربة مستخدم متميزة.',
      'about_p2': 'من تشغيل AstraPlay المتسارع بالأجهزة إلى المزامنة الخلفية الأصلية لـ Hisn Al Muslim، أدفع حدود ما هو ممكن مع أطر العمل متعددة المنصات.',
      'skills_title': 'التقنيات الأساسية',
      'skills_subtitle': 'الأدوات التي أستخدمها لبناء منتجات عالمية المستوى.',
      'projects_title': 'أعمال مختارة',
      'contact_title': 'لنواصل الاتصال',
      'contact_subtitle': 'هل أنت مهتم بالتعاون أو لديك سؤال تقني؟ تواصل معي عبر أي من المنصات أدناه.',
      'back_to_projects': 'العودة للمشاريع',
      'project_resources': 'الموارد والروابط',
      'project_role': 'الدور',
      'project_tech': 'التقنيات',
      'project_live': 'مباشر',
      'project_role_lead': 'كبير المهندسين',
      'project_status_prod': 'جاهز للإنتاج',
      'footer_rights': 'بني باستخدام Flutter Web.',
      'skill_flutter': 'فلاتر',
      'skill_kotlin': 'كوتلن',
      'skill_isar': 'آيسر / إس كيو لايت',
      'skill_firebase': 'فايربيز',
      'skill_ai': 'تكامل الذكاء الاصطناعي',
      'skill_perf': 'الأداء والأمان',
      'contact_email_label': 'البريد الإلكتروني',
      'contact_linkedin_label': 'لينكد إن',
      'contact_github_label': 'جيت هاب',
      'connect_button': 'اتصال',
    },
    'es': {
      'nav_work': 'TRABAJO',
      'nav_about': 'SOBRE MÍ',
      'nav_services': 'SERVICIOS',
      'nav_talk': 'HABLEMOS',
      'hero_badge': 'DISPONIBLE PARA NUEVAS OPORTUNIDADES',
      'hero_title': 'Mohamed Taha',
      'hero_subtitle': 'Arquitecto de Software Senior',
      'hero_description': 'Creando ecosistemas digitales resilientes y de alto rendimiento con Flutter, Android Native e integraciones de IA de vanguardia.',
      'hero_cta_primary': 'Explorar Proyectos',
      'hero_cta_secondary': 'Contactar',
      'about_label': 'Filosofía',
      'about_title': 'Ingeniería para el\nFuturo de la Movilidad y la IA.',
      'about_p1': 'Mi trabajo se define por la intersección de la ingeniería rigurosa y el diseño intuitivo. Con un enfoque en aplicaciones críticas de rendimiento, construyo sistemas lo suficientemente robustos para producción pero lo suficientemente fluidos para una experiencia de usuario premium.',
      'about_p2': 'Desde la reproducción acelerada por hardware de AstraPlay hasta la sincronización de fondo nativa de Hisn Al Muslim, supero los límites de lo posible con marcos multiplataforma.',
      'skills_title': 'Stack Principal',
      'skills_subtitle': 'Las herramientas que utilizo para crear productos de clase mundial.',
      'projects_title': 'Trabajos Seleccionados',
      'contact_title': 'Conectemos',
      'contact_subtitle': '¿Interesado en colaborar o tienes una pregunta técnica? Contáctame a través de cualquiera de las plataformas a continuación.',
      'back_to_projects': 'Volver a Proyectos',
      'project_resources': 'Recursos y Enlaces',
      'project_role': 'Rol',
      'project_tech': 'Tecnologías',
      'project_live': 'En Vivo',
      'project_role_lead': 'Ingeniero Principal',
      'project_status_prod': 'Listo para Producción',
      'footer_rights': 'Construido con Flutter Web.',
      'skill_flutter': 'Flutter',
      'skill_kotlin': 'Kotlin',
      'skill_isar': 'Isar/SQLite',
      'skill_firebase': 'Firebase',
      'skill_ai': 'Integración de IA',
      'skill_perf': 'Perf/Seguridad',
      'contact_email_label': 'Correo',
      'contact_linkedin_label': 'LinkedIn',
      'contact_github_label': 'GitHub',
      'connect_button': 'Conectar',
    },
    'fr': {
      'nav_work': 'TRAVAUX',
      'nav_about': 'À PROPOS',
      'nav_services': 'SERVICES',
      'nav_talk': 'DISCUTONS',
      'hero_badge': 'DISPONIBLE POUR DE NOUVELLES OPPORTUNITÉS',
      'hero_title': 'Mohamed Taha',
      'hero_subtitle': 'Architecte Logiciel Senior',
      'hero_description': 'Conception d\'écosystèmes numériques résilients et performants avec Flutter, Android Native et des intégrations IA de pointe.',
      'hero_cta_primary': 'Explorer les Projets',
      'hero_cta_secondary': 'Me Contacter',
      'about_label': 'Philosophie',
      'about_title': 'L\'ingénierie pour l\'avenir\nde la mobilité et de l\'IA.',
      'about_p1': 'Mon travail est défini par l\'intersection d\'une ingénierie rigoureuse et d\'un design intuitif. En me concentrant sur les applications critiques en termes de performances, je construis des systèmes suffisamment robustes pour la production mais assez fluides pour une expérience utilisateur premium.',
      'about_p2': 'De la lecture accélérée par matériel d\'AstraPlay à la synchronisation d\'arrière-plan native de Hisn Al Muslim, je repousse les limites du possible avec des frameworks multiplateformes.',
      'skills_title': 'Stack Technique',
      'skills_subtitle': 'Les outils que j\'utilise pour créer des produits de classe mondiale.',
      'projects_title': 'Travaux Sélectionnés',
      'contact_title': 'Connectons-nous',
      'contact_subtitle': 'Intéressé par une collaboration ou une question technique ? Contactez-moi via l\'une des plateformes ci-dessous.',
      'back_to_projects': 'Retour aux Projets',
      'project_resources': 'Ressources et Liens',
      'project_role': 'Rôle',
      'project_tech': 'Technologies',
      'project_live': 'En Direct',
      'project_role_lead': 'Ingénieur Principal',
      'project_status_prod': 'Prêt pour la Production',
      'footer_rights': 'Construit avec Flutter Web.',
      'skill_flutter': 'Flutter',
      'skill_kotlin': 'Kotlin',
      'skill_isar': 'Isar/SQLite',
      'skill_firebase': 'Firebase',
      'skill_ai': 'Intégration IA',
      'skill_perf': 'Perf/Sécurité',
      'contact_email_label': 'Email',
      'contact_linkedin_label': 'LinkedIn',
      'contact_github_label': 'GitHub',
      'connect_button': 'Connecter',
    },
    'de': {
      'nav_work': 'PROJEKTE',
      'nav_about': 'ÜBER MICH',
      'nav_services': 'SERVICES',
      'nav_talk': 'KONTAKT',
      'hero_badge': 'VERFÜGBAR FÜR NEUE OPPORTUNITÄTEN',
      'hero_title': 'Mohamed Taha',
      'hero_subtitle': 'Senior Software Architekt',
      'hero_description': 'Entwicklung widerstandsfähiger, leistungsstarker digitaler Ökosysteme mit Flutter, Android Native und modernsten KI-Integrationen.',
      'hero_cta_primary': 'Projekte Erkunden',
      'hero_cta_secondary': 'Kontakt Aufnehmen',
      'about_label': 'Philosophie',
      'about_title': 'Engineering für die Zukunft\nvon Mobilität und KI.',
      'about_p1': 'Meine Arbeit ist geprägt von der Schnittstelle zwischen rigorosem Engineering und intuitivem Design. Mit Fokus auf performancekritische Anwendungen baue ich Systeme, die robust genug für die Produktion, aber flüssig genug für ein erstklassiges Nutzererlebnis sind.',
      'about_p2': 'Von der hardwarebeschleunigten Wiedergabe bei AstraPlay bis zur nativen Hintergrundsynchronisation bei Hisn Al Muslim verschiebe ich die Grenzen dessen, was mit plattformübergreifenden Frameworks möglich ist.',
      'skills_title': 'Kern-Technologien',
      'skills_subtitle': 'Die Werkzeuge, die ich verwende, um erstklassige Produkte zu bauen.',
      'projects_title': 'Ausgewählte Arbeiten',
      'contact_title': 'Lass uns vernetzen',
      'contact_subtitle': 'Interesse an einer Zusammenarbeit oder eine technische Frage? Melde dich über eine der unten stehenden Plattformen.',
      'back_to_projects': 'Zurück zu den Projekten',
      'project_resources': 'Ressourcen & Links',
      'project_role': 'Rolle',
      'project_tech': 'Technologien',
      'project_live': 'Live',
      'project_role_lead': 'Leitender Ingenieur',
      'project_status_prod': 'Produktionsreif',
      'footer_rights': 'Erstellt mit Flutter Web.',
      'skill_flutter': 'Flutter',
      'skill_kotlin': 'Kotlin',
      'skill_isar': 'Isar/SQLite',
      'skill_firebase': 'Firebase',
      'skill_ai': 'KI-Integration',
      'skill_perf': 'Perf/Sicherheit',
      'contact_email_label': 'E-Mail',
      'contact_linkedin_label': 'LinkedIn',
      'contact_github_label': 'GitHub',
      'connect_button': 'Vernetzen',
    },
    'zh': {
      'nav_work': '项目',
      'nav_about': '关于',
      'nav_services': '服务',
      'nav_talk': '联系我',
      'hero_badge': '寻找新机会',
      'hero_title': 'Mohamed Taha',
      'hero_subtitle': '高级软件架构师',
      'hero_description': '利用 Flutter、Android 原生开发和前沿 AI 集成，打造具有弹性、高性能的数字生态系统。',
      'hero_cta_primary': '探索项目',
      'hero_cta_secondary': '取得联系',
      'about_label': '理念',
      'about_title': '为移动与人工智能的未来而工程。',
      'about_p1': '我的工作定义在严谨的工程与直观的设计交汇处。专注于性能关键型应用，我构建的系统既足够强大以应对生产环境，又足够流畅以提供优质的用户体验。',
      'about_p2': '从 AstraPlay 的硬件加速播放到 Hisn Al Muslim 的原生后台同步，我利用跨平台框架不断挑战可能性的极限。',
      'skills_title': '核心技术栈',
      'skills_subtitle': '我用来构建世界级产品的工具。',
      'projects_title': '精选作品',
      'contact_title': '建立联系',
      'contact_subtitle': '对合作感兴趣或有技术问题？请通过以下任何平台与我联系。',
      'back_to_projects': '返回项目',
      'project_resources': '资源与链接',
      'project_role': '角色',
      'project_tech': '技术栈',
      'project_live': '上线',
      'project_role_lead': '首席工程师',
      'project_status_prod': '生产就绪',
      'footer_rights': '使用 Flutter Web 构建。',
      'skill_flutter': 'Flutter',
      'skill_kotlin': 'Kotlin',
      'skill_isar': 'Isar/SQLite',
      'skill_firebase': 'Firebase',
      'skill_ai': '人工智能集成',
      'skill_perf': '性能与安全',
      'contact_email_label': '电子邮箱',
      'contact_linkedin_label': '领英',
      'contact_github_label': 'GitHub',
      'connect_button': '联系',
    },
    'ja': {
      'nav_work': '実績',
      'nav_about': '私について',
      'nav_services': 'サービス',
      'nav_talk': 'お問い合わせ',
      'hero_badge': '新しい機会を募集中',
      'hero_title': 'Mohamed Taha',
      'hero_subtitle': 'シニアソフトウェアアーキテクト',
      'hero_description': 'Flutter、Androidネイティブ、および最先端のAI統合を使用して、復元力のある高性能なデジタルエコシステムを構築します。',
      'hero_cta_primary': 'プロジェクトを探索',
      'hero_cta_secondary': '連絡を取る',
      'about_label': '理念',
      'about_title': 'モビリティとAIの未来に向けたエンジニアリング。',
      'about_p1': '私の仕事は、厳格なエンジニアリングと直感的なデザインの交差点によって定義されます。パフォーマンスが重要なアプリケーションに焦点を当て、本番環境に耐えうる堅牢性と、プレミアムなユーザー体験を実現する流動性を兼ね備えたシステムを構築します。',
      'about_p2': 'AstraPlayのハードウェア加速再生からHisn Al Muslimのネイティブバックグラウンド同期まで、クロスプラットフォームフレームワークで可能なことの限界を押し広げています。',
      'skills_title': 'コアスタック',
      'skills_subtitle': '世界クラスの製品を構築するために使用するツール。',
      'projects_title': '厳選された実績',
      'contact_title': 'つながりましょう',
      'contact_subtitle': 'コラボレーションに興味があるか、技術的な質問がありますか？以下のプラットフォームのいずれかからご連絡ください。',
      'back_to_projects': 'プロジェクトに戻る',
      'project_resources': 'リソースとリンク',
      'project_role': '役割',
      'project_tech': '技術スタック',
      'project_live': 'ライブ',
      'project_role_lead': 'リードエンジニア',
      'project_status_prod': '本番環境対応',
      'footer_rights': 'Flutter Webで構築。',
      'skill_flutter': 'Flutter',
      'skill_kotlin': 'Kotlin',
      'skill_isar': 'Isar/SQLite',
      'skill_firebase': 'Firebase',
      'skill_ai': 'AI統合',
      'skill_perf': 'パフォーマンスとセキュリティ',
      'contact_email_label': 'メール',
      'contact_linkedin_label': 'LinkedIn',
      'contact_github_label': 'GitHub',
      'connect_button': 'つながる',
    },
  };

  static String get(String key, String locale) {
    return _values[locale]?[key] ?? _values['en']![key]!;
  }
}
